apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: oci-mysql-storage
provisioner: blockvolume.csi.oraclecloud.com
parameters:
  fsType: ext4
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true

