existingObjstoreSecret: thanos-objstore

query:
  service:
    type: LoadBalancer
  dnsDiscovery:
    sidecarsService: "prometheus-operated"
    sidecarsNamespace: "default"

compactor:
  enabled: true

storegateway:
  enabled: true

metrics:
  enabled: true
  serviceMonitor:
    enabled: true

