apiVersion: apps/v1
kind: Deployment
metadata: {{ toYaml .Values.basic.meta | nindent 2 }}
spec: {{ toYaml .Values.basic.spec | nindent 2 }}
  template: {{ toYaml .Values.basic.template | nindent 4 }}
    spec:
      containers:
      - name: nginx
        image: nginx:latest  # Replace with your desired nginx image
        ports:
        - containerPort: 80



