apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-deployment  # Replace with your desired deployment name
  labels:
    app: nginx
spec:
  replicas: 1  # Number of nginx pods to create
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest  # Replace with your desired nginx image
        ports:
        - containerPort: 80
