basic:
  meta:
    name: my-nginx-deployment
    labels:
      app: nginx
  spec:
    replicas: 1  # Number of nginx pods to create
    selector:
     matchLabels:
       app: nginx
  template:
    metadata:
      labels:
        app: nginx




